customer = dict(
    MAX_ITEMS=10,
    CARD_PROBABILITY=75,
    LEGAL_AGE=21,
    AGE_PROOF_PROBABILITY=80,
    MAX_CASH_IN_HAND=700
)

item = dict(
    MAX_ITEM_VALUE=20,
    ITEM_ALCOHOL_PROBABILITY=10
)