customer = dict(
    MAX_ITEMS=10,
    CARD_PROBABILITY=50,
    LEGAL_AGE=21,
    AGE_PROOF_PROBABILITY=80,
    MAX_CASH_IN_HAND=500
)

item = dict(
    MAX_ITEM_VALUE=50,
    ITEM_ALCOHOL_PROBABILITY=10
)